AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: amopps-new-bucket
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
